##### BUILDER #####

FROM alpine:3.14 as builder

## Task: Install build deps
RUN apk update
RUN set -eux; \
    apk add --no-progress --quiet --no-cache --upgrade --virtual .build-deps \
        gcc \
        git \
        musl-dev \
        bash

#RUN apk add libstdc++.so.6

WORKDIR /root
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-2.30-r0.apk
RUN apk add --allow-untrusted glibc-2.30-r0.apk
RUN addgroup -S wokwi && adduser -S -G wokwi wokwi

# USER wokwi
WORKDIR /home/wokwi
RUN mkdir -p /home/wokwi/cli
WORKDIR /home/wokwi/cli
RUN wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
RUN tar zxvf arduino-cli_latest_Linux_64bit.tar.gz
RUN rm arduino-cli_latest_Linux_64bit.tar.gz
ENV PATH="/home/wokwi/cli:${PATH}"

# Install AVR core
RUN arduino-cli config init
RUN arduino-cli config add board_manager.additional_urls https://dl.espressif.com/dl/package_esp32_index.json

RUN arduino-cli core update-index
RUN arduino-cli core download esp32:esp32
RUN arduino-cli core install arduino:avr
RUN arduino-cli core install esp32:esp32

# install needed libraries
RUN arduino-cli lib install switch
RUN arduino-cli lib install Servo
#RUN arduino-cli lib install ESP32Servo

## Task: get source files
WORKDIR /home/wokwi
RUN git clone https://github.com/willie68/Arduino_TPS.git

## Task switch to right branch
WORKDIR /home/wokwi/Arduino_TPS/
RUN git pull
RUN git checkout develop

COPY --chown=wokwi:wokwi ./build_tps.sh ./builder/build_tps.sh
RUN chmod u+x ./builder/build_tps.sh

## Task compile versions
WORKDIR /home/wokwi/Arduino_TPS/TPS
RUN mkdir -p /home/wokwi/Arduino_TPS/dest

#RUN ../builder/build_tps.sh